# Generated by Django 5.0.1 on 2024-02-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDetails',
            fields=[
                ('registration_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('manufactured_by', models.CharField(max_length=50)),
                ('vehicle_model', models.CharField(max_length=50)),
                ('year_of_manufacture', models.IntegerField()),
                ('body_built_by', models.CharField(max_length=50)),
                ('type_of_vehicle', models.CharField(max_length=50)),
                ('battery_size', models.CharField(max_length=20)),
                ('tyre_size', models.CharField(max_length=20)),
                ('chassis_number', models.CharField(max_length=30)),
                ('engine_number', models.CharField(max_length=30)),
                ('date_of_delivery', models.DateField()),
                ('order_number', models.CharField(max_length=20)),
                ('kgid_policy_number', models.CharField(max_length=30)),
            ],
        ),
    ]
