# Generated by Django 5.0.1 on 2024-02-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledetails',
            name='location',
            field=models.CharField(default='Jayanagar', max_length=45),
            preserve_default=False,
        ),
    ]
