# Generated by Django 5.0.1 on 2024-02-08 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0002_vehicledetails_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleQR',
            fields=[
                ('registration_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Vehicles.vehicledetails')),
                ('image_blob', models.BinaryField()),
            ],
        ),
    ]
